export const FONTS = [
  { label: 'Default Font', value: '' },
  { label: 'Source Han Sans', value: 'SourceHanSans' },
  { label: 'Source Han Serif', value: 'SourceHanSerif' },
  { label: 'FangZhengHeiTi', value: 'FangZhengHeiTi' },
  { label: 'FangZhengKaiTi', value: 'FangZhengKaiTi' },
  { label: 'FangZhengShuSong', value: 'FangZhengShuSong' },
  { label: 'FangZhengFangSong', value: 'FangZhengFangSong' },
  { label: 'Alibaba PuHuiTi', value: 'AlibabaPuHuiTi' },
  { label: 'Zhuque FangSong', value: 'ZhuqueFangSong' },
  { label: 'LXGW WenKai', value: 'LXGWWenKai' },
  { label: 'WenDing PL KaiTi', value: 'WenDingPLKaiTi' },
  { label: 'DeYiHei', value: 'DeYiHei' },
  { label: 'MiSans', value: 'MiSans' },
  { label: 'Canger Xiaowanzi', value: 'CangerXiaowanzi' },
  { label: 'Youshe Title Black', value: 'YousheTitleBlack' },
  { label: 'Fengguang Mingrui', value: 'FengguangMingrui' },
  { label: 'Shetu Modern Square', value: 'ShetuModernSquare' },
  { label: 'Zcool Happy', value: 'ZcoolHappy' },
  { label: 'ZizhiQu XiMai', value: 'ZizhiQuXiMai' },
  { label: 'SucaiJishi Kangkang', value: 'SucaiJishiKangkang' },
  { label: 'SucaiJishi CoolSquare', value: 'SucaiJishiCoolSquare' },
  { label: 'Tuniu Rounded', value: 'TuniuRounded' },
  { label: 'Ruizi Zhenyan', value: 'RuiziZhenyan' },
];
