export const FONTS = [
  { label: 'Default Font', value: 'sans-serif' },
  { label: 'Roboto', value: 'Roboto' },
  { label: 'Open Sans', value: 'Open Sans' },
  { label: 'Noto Sans JP', value: 'Noto Sans JP' },
  { label: 'Montserrat', value: 'Montserrat' },
  { label: 'Inter', value: 'Inter' },
  { label: 'Roboto Condensed', value: 'Roboto Condensed' },
  { label: 'Roboto Mono', value: 'Roboto Mono' },
  { label: 'Arimo', value: 'Arimo' },
  { label: 'Oswald', value: 'Oswald' },
  { label: 'Noto Sans', value: 'Noto Sans' },
  { label: 'Raleway', value: 'Raleway' },
  { label: 'Nunito Sans', value: 'Nunito Sans' },
  { label: 'Nunito', value: 'Nunito' },
  { label: 'Noto Sans KR', value: 'Noto Sans KR' },
  { label: 'Playfair Display', value: 'Playfair Display' },
  { label: 'Merriweather', value: 'Merriweather' },
  { label: 'Roboto Slab', value: 'Roboto Slab' },
  { label: 'Work Sans', value: 'Work Sans' },
  { label: 'Kanit', value: 'Kanit' },
  { label: 'Noto Sans TC', value: 'Noto Sans TC' },
  { label: 'Quicksand', value: 'Quicksand' },
  { label: 'Lora', value: 'Lora' },
  { label: 'Manrope', value: 'Manrope' },
  { label: 'IBM Plex Sans', value: 'IBM Plex Sans' },
  { label: 'Mulish', value: 'Mulish' },
  { label: 'Fira Sans', value: 'Fira Sans' },
  { label: 'Inconsolata', value: 'Inconsolata' },
  { label: 'Barlow', value: 'Barlow' },
  { label: 'Bungee', value: 'Bungee' },
  { label: 'Noto Serif', value: 'Noto Serif' },
  { label: 'Poppins', value: 'Poppins' },
  { label: 'Comfortaa', value: 'Comfortaa' },
  { label: 'Fredoka', value: 'Fredoka' },
  { label: 'Space Grotesk', value: 'Space Grotesk' },
  { label: 'DM Sans', value: 'DM Sans' },
  { label: 'Lato', value: 'Lato' },
  { label: 'Source Sans Pro', value: 'Source Sans Pro' },
  { label: 'Plus Jakarta Sans', value: 'Plus Jakarta Sans' },
  { label: 'Ubuntu', value: 'Ubuntu' },
  { label: 'Rubik', value: 'Rubik' },
  { label: 'Karla', value: 'Karla' },
  { label: 'PT Sans', value: 'PT Sans' },
  { label: 'Cabin', value: 'Cabin' },
  { label: 'Bitter', value: 'Bitter' },
  { label: 'Hind', value: 'Hind' },
  { label: 'Libre Franklin', value: 'Libre Franklin' },
  { label: 'Oxygen', value: 'Oxygen' },
  { label: 'Archivo', value: 'Archivo' },
  { label: 'Heebo', value: 'Heebo' },
  { label: 'Josefin Sans', value: 'Josefin Sans' },
  { label: 'Titillium Web', value: 'Titillium Web' },
  { label: 'Red Hat Display', value: 'Red Hat Display' },
  { label: 'Exo 2', value: 'Exo 2' },
  { label: 'Lexend', value: 'Lexend' },
  { label: 'Be Vietnam Pro', value: 'Be Vietnam Pro' },
  { label: 'Arial', value: 'Arial' },
  { label: 'Verdana', value: 'Verdana' },
  { label: 'Georgia', value: 'Georgia' },
  { label: 'Times New Roman', value: 'Times New Roman' },
  { label: 'Courier New', value: 'Courier New' },
  { label: 'Trebuchet MS', value: 'Trebuchet MS' },
  { label: 'Prompt', value: 'Prompt' },
  { label: 'Fjalla One', value: 'Fjalla One' },
  { label: 'Source Sans 3', value: 'Source Sans 3' },
  { label: 'Source Code Pro', value: 'Source Code Pro' },
  { label: 'Saira', value: 'Saira' },
  { label: 'Dancing Script', value: 'Dancing Script' },
  { label: 'Noto Sans SC', value: 'Noto Sans SC' },
  { label: 'Noto Serif JP', value: 'Noto Serif JP' },
  { label: 'Bricolage Grotesque', value: 'Bricolage Grotesque' },
  { label: 'Roboto Flex', value: 'Roboto Flex' },
  { label: 'Dosis', value: 'Dosis' },
  { label: 'Anton', value: 'Anton' },
  { label: 'EB Garamond', value: 'EB Garamond' },
  { label: 'Public Sans', value: 'Public Sans' },
  { label: 'Barlow Condensed', value: 'Barlow Condensed' },
  { label: 'Crimson Text', value: 'Crimson Text' },
  { label: 'Pacifico', value: 'Pacifico' },
  { label: 'Alfa Slab One', value: 'Alfa Slab One' },
  { label: 'Lobster', value: 'Lobster' },
  { label: 'Cormorant Garamond', value: 'Cormorant Garamond' },
  { label: 'Overpass', value: 'Overpass' },
  { label: 'Inter Tight', value: 'Inter Tight' },
  { label: 'Maven Pro', value: 'Maven Pro' },
  { label: 'Barlow Semi Condensed', value: 'Barlow Semi Condensed' },
  { label: 'Play', value: 'Play' },
  { label: 'Merriweather Sans', value: 'Merriweather Sans' },
  { label: 'Asap', value: 'Asap' },
  { label: 'IBM Plex Mono', value: 'IBM Plex Mono' },
  { label: 'Noto Sans HK', value: 'Noto Sans HK' },
  { label: 'Varela Round', value: 'Varela Round' },
  { label: 'Lexend Deca', value: 'Lexend Deca' },
  { label: 'Questrial', value: 'Questrial' },
  { label: 'Source Serif 4', value: 'Source Serif 4' },
  { label: 'IBM Plex Serif', value: 'IBM Plex Serif' },
  { label: 'JetBrains Mono', value: 'JetBrains Mono' },
  { label: 'Roboto Serif', value: 'Roboto Serif' },
  { label: 'League Spartan', value: 'League Spartan' },
  { label: 'Crimson Pro', value: 'Crimson Pro' },
  { label: 'Hanken Grotesk', value: 'Hanken Grotesk' },
  { label: 'Commissioner', value: 'Commissioner' },
  { label: 'Epilogue', value: 'Epilogue' },
  { label: 'Literata', value: 'Literata' },
  { label: 'Noto Sans Mono', value: 'Noto Sans Mono' },
  { label: 'Reddit Sans', value: 'Reddit Sans' },
];
