export const FONTS = [
  { label: 'Default Font', value: 'sans-serif' },
  { label: 'Roboto', value: 'Roboto' },
  { label: 'Open Sans', value: 'Open Sans' },
  { label: 'Noto Sans JP', value: 'Noto Sans JP' },
  { label: 'Montserrat', value: 'Montserrat' },
  { label: 'Inter', value: 'Inter' },
  { label: 'Roboto Condensed', value: 'Roboto Condensed' },
  { label: 'Roboto Mono', value: 'Roboto Mono' },
  { label: 'Arimo', value: 'Arimo' },
  { label: 'Oswald', value: 'Oswald' },
  { label: 'Noto Sans', value: 'Noto Sans' },
  { label: 'Raleway', value: 'Raleway' },
  { label: 'Nunito Sans', value: 'Nunito Sans' },
  { label: 'Nunito', value: 'Nunito' },
  { label: 'Noto Sans KR', value: 'Noto Sans KR' },
  { label: 'Playfair Display', value: 'Playfair Display' },
  { label: 'Merriweather', value: 'Merriweather' },
  { label: 'Roboto Slab', value: 'Roboto Slab' },
  { label: 'Work Sans', value: 'Work Sans' },
  { label: 'Kanit', value: 'Kanit' },
  { label: 'Noto Sans TC', value: 'Noto Sans TC' },
  { label: 'Quicksand', value: 'Quicksand' },
  { label: 'Lora', value: 'Lora' },
  { label: 'Manrope', value: 'Manrope' },
  { label: 'IBM Plex Sans', value: 'IBM Plex Sans' },
  { label: 'Mulish', value: 'Mulish' },
  { label: 'Fira Sans', value: 'Fira Sans' },
  { label: 'Inconsolata', value: 'Inconsolata' },
  { label: 'Barlow', value: 'Barlow' },
  { label: 'Bungee', value: 'Bungee' },
  { label: 'Noto Serif', value: 'Noto Serif' },
  { label: 'Poppins', value: 'Poppins' },
  { label: 'Comfortaa', value: 'Comfortaa' },
  { label: 'Fredoka', value: 'Fredoka' },
  { label: 'Space Grotesk', value: 'Space Grotesk' },
  { label: 'DM Sans', value: 'DM Sans' },
];
