openapi: 3.0.0
info:
  title: Teacher Schedule API
  version: 1.0.0
paths:
  /api/classes/{classId}/calendar/events:
    get:
      summary: Get calendar events for a class
      parameters:
        - name: classId
          in: path
          required: true
          schema:
            type: string
        - name: startDate
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: A list of calendar events
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCalendarEventsResponse'
components:
  schemas:
    ScheduleEvent:
      type: object
      properties:
        id:
          type: string
        classId:
          type: string
        name:
          type: string
        subject:
          type: string
        subjectCode:
          type: string
        date:
          type: string
          format: date
        startTime:
          type: string
          format: time
        endTime:
          type: string
          format: time
        category:
          type: string
        location:
          type: string
        description:
          type: string
        isActive:
          type: boolean
        lessonPlanId:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    GetCalendarEventsResponse:
      type: object
      properties:
        events:
          type: array
          items:
            $ref: '#/components/schemas/ScheduleEvent'
