openapi: 3.0.3
info:
  title: Class Calendar Events API
  description: API for fetching calendar events for a specific class
  version: 1.0.0
  contact:
    name: DATN FE Team

servers:
  - url: http://localhost:3000/api
    description: Local development server
  - url: https://api.example.com/api
    description: Production server (TBD)

paths:
  /classes/{classId}/events:
    get:
      summary: Get calendar events for a class
      description: |
        Retrieves all calendar events for a specific class within a date range.
        Used by the calendar view to display events for the selected month.
      operationId: getClassEvents
      tags:
        - Calendar
      parameters:
        - name: classId
          in: path
          required: true
          description: Unique identifier of the class
          schema:
            type: string
            format: uuid
            example: '123e4567-e89b-12d3-a456-426614174000'
        
        - name: startDate
          in: query
          required: true
          description: Start date of the range (inclusive) in ISO 8601 format
          schema:
            type: string
            format: date
            example: '2025-10-01'
        
        - name: endDate
          in: query
          required: true
          description: End date of the range (inclusive) in ISO 8601 format
          schema:
            type: string
            format: date
            example: '2025-10-31'
        
        - name: category
          in: query
          required: false
          description: Filter events by category (optional)
          schema:
            type: string
            enum:
              - assignment
              - exam
              - fieldTrip
              - meeting
              - holiday
              - presentation
              - other
            example: 'fieldTrip'
      
      responses:
        '200':
          description: Successful response with events
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalendarEventsResponse'
              examples:
                withEvents:
                  summary: Month with multiple events
                  value:
                    events:
                      - id: 'event-001'
                        classId: '123e4567-e89b-12d3-a456-426614174000'
                        name: 'Book Report Due'
                        date: '2025-10-20'
                        startTime: null
                        endTime: null
                        category: 'assignment'
                        location: null
                        description: 'Submit book report on assigned reading'
                        createdAt: '2025-09-01T10:00:00Z'
                        updatedAt: '2025-09-01T10:00:00Z'
                      - id: 'event-002'
                        classId: '123e4567-e89b-12d3-a456-426614174000'
                        name: 'Field Trip'
                        date: '2025-10-25'
                        startTime: '08:00:00'
                        endTime: '15:00:00'
                        category: 'fieldTrip'
                        location: 'City Science Museum'
                        description: 'Educational trip to explore science exhibits'
                        createdAt: '2025-09-15T14:30:00Z'
                        updatedAt: '2025-09-15T14:30:00Z'
                noEvents:
                  summary: Month with no events
                  value:
                    events: []
        
        '400':
          description: Bad request - invalid parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: 'Invalid date format'
                message: 'startDate must be in YYYY-MM-DD format'
                statusCode: 400
        
        '404':
          description: Class not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: 'Class not found'
                message: 'No class exists with ID: 123e4567-e89b-12d3-a456-426614174000'
                statusCode: 404
        
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: 'Internal server error'
                message: 'An unexpected error occurred'
                statusCode: 500

components:
  schemas:
    CalendarEventsResponse:
      type: object
      required:
        - events
      properties:
        events:
          type: array
          items:
            $ref: '#/components/schemas/CalendarEvent'
          description: Array of calendar events within the specified date range
    
    CalendarEvent:
      type: object
      required:
        - id
        - classId
        - name
        - date
        - category
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the event
          example: 'event-001'
        
        classId:
          type: string
          format: uuid
          description: Foreign key linking to the class
          example: '123e4567-e89b-12d3-a456-426614174000'
        
        name:
          type: string
          minLength: 1
          maxLength: 100
          description: Event title displayed on calendar
          example: 'Book Report Due'
        
        date:
          type: string
          format: date
          description: Event date in ISO 8601 format (YYYY-MM-DD)
          example: '2025-10-20'
        
        startTime:
          type: string
          format: time
          nullable: true
          description: Optional start time in ISO 8601 format (HH:mm:ss)
          example: '08:00:00'
        
        endTime:
          type: string
          format: time
          nullable: true
          description: Optional end time in ISO 8601 format (HH:mm:ss)
          example: '15:00:00'
        
        category:
          type: string
          enum:
            - assignment
            - exam
            - fieldTrip
            - meeting
            - holiday
            - presentation
            - other
          description: Event category for visual distinction
          example: 'fieldTrip'
        
        location:
          type: string
          maxLength: 200
          nullable: true
          description: Optional physical location
          example: 'City Science Museum'
        
        description:
          type: string
          maxLength: 2000
          nullable: true
          description: Optional detailed description
          example: 'Educational trip to explore science exhibits'
        
        createdAt:
          type: string
          format: date-time
          description: Timestamp when event was created
          example: '2025-09-15T14:30:00Z'
        
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when event was last updated
          example: '2025-09-15T14:30:00Z'
    
    ErrorResponse:
      type: object
      required:
        - error
        - message
        - statusCode
      properties:
        error:
          type: string
          description: Short error identifier
          example: 'Invalid date format'
        
        message:
          type: string
          description: Human-readable error message
          example: 'startDate must be in YYYY-MM-DD format'
        
        statusCode:
          type: integer
          description: HTTP status code
          example: 400

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token for authentication (future implementation)

security:
  - bearerAuth: []

tags:
  - name: Calendar
    description: Calendar events management for classes
