/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alpha: typeof import('./src/components/ColorPicker/Alpha.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    ButtonGroup: typeof import('./src/components/ButtonGroup.vue')['default']
    Checkboard: typeof import('./src/components/ColorPicker/Checkboard.vue')['default']
    Checkbox: typeof import('./src/components/Checkbox.vue')['default']
    CheckboxButton: typeof import('./src/components/CheckboxButton.vue')['default']
    ColorButton: typeof import('./src/components/ColorButton.vue')['default']
    ColorListButton: typeof import('./src/components/ColorListButton.vue')['default']
    ColorPicker: typeof import('./src/components/ColorPicker/index.vue')['default']
    Contextmenu: typeof import('./src/components/Contextmenu/index.vue')['default']
    Divider: typeof import('./src/components/Divider.vue')['default']
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    EditableInput: typeof import('./src/components/ColorPicker/EditableInput.vue')['default']
    FileInput: typeof import('./src/components/FileInput.vue')['default']
    FormulaContent: typeof import('./src/components/LaTeXEditor/FormulaContent.vue')['default']
    FullscreenSpin: typeof import('./src/components/FullscreenSpin.vue')['default']
    GradientBar: typeof import('./src/components/GradientBar.vue')['default']
    Hue: typeof import('./src/components/ColorPicker/Hue.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    LaTeXEditor: typeof import('./src/components/LaTeXEditor/index.vue')['default']
    MenuContent: typeof import('./src/components/Contextmenu/MenuContent.vue')['default']
    Message: typeof import('./src/components/Message.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    MoveablePanel: typeof import('./src/components/MoveablePanel.vue')['default']
    NumberInput: typeof import('./src/components/NumberInput.vue')['default']
    OutlineEditor: typeof import('./src/components/OutlineEditor.vue')['default']
    Popover: typeof import('./src/components/Popover.vue')['default']
    PopoverMenuItem: typeof import('./src/components/PopoverMenuItem.vue')['default']
    RadioButton: typeof import('./src/components/RadioButton.vue')['default']
    RadioGroup: typeof import('./src/components/RadioGroup.vue')['default']
    Saturation: typeof import('./src/components/ColorPicker/Saturation.vue')['default']
    Select: typeof import('./src/components/Select.vue')['default']
    SelectCustom: typeof import('./src/components/SelectCustom.vue')['default']
    SelectGroup: typeof import('./src/components/SelectGroup.vue')['default']
    Slider: typeof import('./src/components/Slider.vue')['default']
    Switch: typeof import('./src/components/Switch.vue')['default']
    SymbolContent: typeof import('./src/components/LaTeXEditor/SymbolContent.vue')['default']
    Tabs: typeof import('./src/components/Tabs.vue')['default']
    TextArea: typeof import('./src/components/TextArea.vue')['default']
    TextColorButton: typeof import('./src/components/TextColorButton.vue')['default']
    WritingBoard: typeof import('./src/components/WritingBoard.vue')['default']
  }
}
