export { DashboardPage } from './DashboardPage';
export { FAQPostsPage } from './FAQPostsPage';
export { GlobalConfigPage } from './GlobalConfigPage';
export { LoginPage } from './LoginPage';
export { ModelConfigPage } from './ModelConfigPage';
export { SlideTemplatesPage } from './SlideTemplatesPage';
export { SlideThemesPage } from './SlideThemesPage';
export { UserDetailPage } from './UserDetailPage';
export { UsersPage } from './UsersPage';
