import type { App } from 'vue';
import {
  Play,
  Maximize,
  Lock,
  Unlock,
  Presentation,
  Type,
  Image,
  Expand,
  List,
  ListOrdered,
  FlipVertical,
  FlipHorizontal,
  Code,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Edit,
  Quote,
  Palette,
  Group,
  Ungroup,
  ArrowLeft,
  ArrowRight,
  Maximize2,
  AlignStartVertical,
  AlignStartHorizontal,
  AlignEndHorizontal,
  AlignEndVertical,
  AlignCenterVertical,
  AlignCenterHorizontal,
  BringToFront,
  SendToBack,
  Send,
  AlignLeft,
  AlignRight,
  AlignCenter,
  AlignJustify,
  RowsIcon,
  PenTool,
  Table,
  PaintBucket,
  Crop,
  Zap,
  Filter,
  ChevronUp,
  ChevronDown,
  Plus,
  Minus,
  Github,
  PieChart,
  BarChart,
  BarChart2,
  AreaChart,
  Activity,
  ChartScatter,
  TrendingUp,
  Radar,
  RotateCw,
  ChevronLeft,
  ChevronRight,
  X,
  XCircle,
  Undo,
  Move,
  MousePointer,
  ArrowLeftCircle,
  Shapes,
  LogOut,
  Eraser,
  Trash,
  Pause,
  VolumeX,
  Volume2,
  Volume1,
  Video,
  Link,
  Minimize,
  Power,
  LayoutList,
  Wand2,
  Highlighter,
  Download,
  IndentIncrease,
  IndentDecrease,
  AlignVerticalSpaceAround,
  Copy,
  Square,
  Circle,
  Compass,
  RotateCcw,
  Paintbrush2,
  Eye,
  EyeOff,
  Timer,
  Search,
  Menu,
  AlertTriangle,
  Check,
  Info,
  MessageSquare,
  User,
  ToggleLeft,
  MoreHorizontal,
  Grid3X3,
  TypeIcon,
  LineSquiggle,
  MousePointer2,
  Sigma,
  Undo2,
  Redo2,
  SwatchBook,
  SkipBack,
  PlayCircle,
  SplitSquareHorizontal,
  ExternalLink,
} from 'lucide-vue-next';

export interface Icons {
  [key: string]: typeof Play;
}

export const icons: Icons = {
  IconPlayOne: Play,
  IconFullScreenPlay: Maximize,
  IconLock: Lock,
  IconUnlock: Unlock,
  IconPpt: Presentation,
  IconFormat: Type,
  IconPicture: Image,
  IconFullScreen: Expand,
  IconList: List,
  IconOrderedList: ListOrdered,
  IconFlipVertically: FlipVertical,
  IconFlipHorizontally: FlipHorizontal,
  IconFontSize: TypeIcon,
  IconCode: Code,
  IconTextBold: Bold,
  IconTextItalic: Italic,
  IconTextUnderline: Underline,
  IconStrikethrough: Strikethrough,
  IconEdit: Edit,
  IconQuote: Quote,
  IconBackgroundColor: Palette,
  IconGroup: Group,
  IconUngroup: Ungroup,
  IconBack: Undo2,
  IconNext: Redo2,
  IconFullwidth: Maximize2,
  IconAlignTop: AlignStartVertical,
  IconAlignLeft: AlignStartHorizontal,
  IconAlignRight: AlignEndHorizontal,
  IconAlignBottom: AlignEndVertical,
  IconAlignVertically: AlignCenterVertical,
  IconAlignHorizontally: AlignCenterHorizontal,
  IconBringToFront: BringToFront,
  IconSendToBack: SendToBack,
  IconSend: Send,
  IconAlignTextLeft: AlignLeft,
  IconAlignTextRight: AlignRight,
  IconAlignTextCenter: AlignCenter,
  IconAlignTextBoth: AlignJustify,
  IconRowHeight: RowsIcon,
  IconWrite: PenTool,
  IconInsertTable: Table,
  IconAddText: Type,
  IconFill: PaintBucket,
  IconTailoring: Crop,
  IconEffects: Zap,
  IconColorFilter: Filter,
  IconUp: ChevronUp,
  IconDown: ChevronDown,
  IconPlus: Plus,
  IconMinus: Minus,
  IconConnection: LineSquiggle,
  IconBringToFrontOne: BringToFront,
  IconSentToBack: SendToBack,
  IconGithub: Github,
  IconChartProportion: PieChart,
  IconChartHistogram: BarChart,
  IconChartHistogramOne: BarChart2,
  IconChartLineArea: AreaChart,
  IconChartRing: Activity,
  IconChartScatter: ChartScatter,
  IconChartLine: TrendingUp,
  IconChartPie: PieChart,
  IconRadarChart: Radar,
  IconText: Type,
  IconRotate: RotateCw,
  IconLeftTwo: ChevronLeft,
  IconRightTwo: ChevronRight,
  IconPalette: Palette,
  IconClose: X,
  IconCloseSmall: XCircle,
  IconUndo: Undo,
  IconTransform: Move,
  IconClick: MousePointer,
  IconTheme: Palette,
  IconArrowCircleLeft: ArrowLeftCircle,
  IconArrowRight: ArrowRight,
  IconGraphicDesign: Shapes,
  IconLogout: LogOut,
  IconErase: Eraser,
  IconClear: Trash,
  IconAlignTextTopOne: AlignStartVertical,
  IconAlignTextBottomOne: AlignEndVertical,
  IconAlignTextMiddleOne: AlignCenterVertical,
  IconPause: Pause,
  IconVolumeMute: VolumeX,
  IconVolumeNotice: Volume2,
  IconVolumeSmall: Volume1,
  IconVideoTwo: Video,
  IconFormula: Sigma,
  IconLinkOne: Link,
  IconFullScreenOne: Maximize,
  IconOffScreenOne: Minimize,
  IconPower: Power,
  IconListView: LayoutList,
  IconMagic: Wand2,
  IconHighLight: Highlighter,
  IconDownload: Download,
  IconIndentLeft: IndentIncrease,
  IconIndentRight: IndentDecrease,
  IconVerticalSpacingBetweenItems: AlignVerticalSpaceAround,
  IconCopy: Copy,
  IconDelete: Trash,
  IconSquare: Square,
  IconRound: Circle,
  IconNeedle: Compass,
  IconTextRotationNone: RotateCcw,
  IconTextRotationDown: RotateCw,
  IconFormatBrush: Paintbrush2,
  IconPreviewOpen: Eye,
  IconPreviewClose: EyeOff,
  IconStopwatchStart: Timer,
  IconSearch: Search,
  IconLeft: ArrowLeft,
  IconRight: ArrowRight,
  IconMoveOne: MousePointer2,
  IconHamburgerButton: Menu,
  IconAttention: AlertTriangle,
  IconCheckOne: Check,
  IconCloseOne: X,
  IconInfo: Info,
  IconComment: MessageSquare,
  IconUser: User,
  IconSwitch: ToggleLeft,
  IconMore: MoreHorizontal,
  IconMoreApp: Grid3X3,
  IconSwatchBook: SwatchBook,
  IconPresentFromStart: SkipBack,
  IconPresentFromCurrent: PlayCircle,
  IconPresenterView: SplitSquareHorizontal,
  IconPresentSeparated: ExternalLink,
};

export default {
  install(app: App) {
    for (const key of Object.keys(icons)) {
      app.component(key, icons[key]);
    }
  },
};
