openapi: 3.0.0
info:
  title: Subject Context View API
  version: 1.0.0
paths:
  /api/classes/{classId}/subjects:
    get:
      summary: Get all subjects for a class
      parameters:
        - name: classId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of subjects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subject'
  /api/classes/{classId}/subjects/{subjectId}/periods:
    get:
      summary: Get all periods for a subject
      parameters:
        - name: classId
          in: path
          required: true
          schema:
            type: string
        - name: subjectId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of periods for the subject
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Period'
components:
  schemas:
    Subject:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    Period:
      type: object
      properties:
        id:
          type: string
        date:
          type: string
          format: date
        startTime:
          type: string
          format: time
        endTime:
          type: string
          format: time
        lesson:
          $ref: '#/components/schemas/Lesson'
    Lesson:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
