#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Capture the list of staged files
STAGED_FILES=$(git diff --cached --name-only)

# Run formatting
pnpm format

# Re-add the originally staged files (now formatted) back to staging
if [ -n "$STAGED_FILES" ]; then
  echo "$STAGED_FILES" | xargs git add
fi