#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Capture the list of staged files (excluding deleted files)
STAGED_FILES=$(git diff --cached --name-only --diff-filter=d)

# Run formatting
pnpm format

# Re-add the originally staged files (now formatted) back to staging
if [ -n "$STAGED_FILES" ]; then
  echo "$STAGED_FILES" | xargs git add
fi